plugins {
    id 'com.gradleup.shadow' version '9.2.2'
    id 'application'
}

group = 'org.example'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation 'org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.5.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}

compileJava {
    options.release = 11
}

application {
    mainClass = 'org.hyperledger.fabric.contract.ContractRouter'
}

shadowJar {
    archiveBaseName = 'chaincode'
    archiveVersion = ''
    archiveClassifier = ''
    mergeServiceFiles()

    manifest {
        attributes 'Main-Class': 'org.hyperledger.fabric.contract.ContractRouter'
    }
}

tasks.named('build') {
    dependsOn shadowJar
}
